/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sanyukta
 * 
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class test_marksRetrieve extends javax.swing.JFrame {

    /**
     * Creates new form test_marksRetrieve
     */
    public test_marksRetrieve() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Student ID:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Std:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8th", "9th", "10th", "11th", "12th" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)
                                .addComponent(jButton1))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        fetch();
    }//GEN-LAST:event_jButton1ActionPerformed

      private void fetch()
    {
        String sid=jTextField1.getText();
        int flag=0; 
        
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            if(jComboBox1.getSelectedItem().equals("8th")){
            String sql="select test_marks.sid,students.sname,test_marks.english,marathi,hindi,science,history,geography,maths from students inner join test_marks on students.sid=test_marks.sid and students.sid='"+jTextField1.getText()+"' and test_marks.std='"+jComboBox1.getSelectedItem()+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else{
            JOptionPane.showMessageDialog(this,"Record  not found");
            }
            }
            /*else{
                JOptionPane.showMessageDialog(this,"Record already exist!");
               
            }*/
            else if(jComboBox1.getSelectedItem().equals("9th")){
                
            String sql="select test_marks.sid,students.sname,test_marks.english,marathi,hindi,science,history,geography,algebra,geometry,sanskrit from students inner join test_marks on students.sid=test_marks.sid and students.sid='"+jTextField1.getText()+"' and test_marks.std='"+jComboBox1.getSelectedItem()+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            //if(jComboBox1.getSelectedItem().equals("9th")){}
            
             if(rs.next()){
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else{
            JOptionPane.showMessageDialog(this,"Record  not found");
            }
            
            }
            /*else{
                JOptionPane.showMessageDialog(this,"Record already exist!");
            }*/
            else if(jComboBox1.getSelectedItem().equals("10th")){
            String sql="select test_marks.sid,students.sname,test_marks.english,marathi,hindi,science,history,geography,algebra,geometry,sanskrit from students inner join test_marks on students.sid=test_marks.sid and students.sid='"+jTextField1.getText()+"' and test_marks.std='"+jComboBox1.getSelectedItem()+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
             if(rs.next()){
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else{
            JOptionPane.showMessageDialog(this,"Record  not found");
            }
            }
            /*else{
               JOptionPane.showMessageDialog(this,"Record already exist!");
            }*/
            else if(jComboBox1.getSelectedItem().equals("11th")){ 
        
            String sql="select test_marks.sid,students.sname,test_marks.english,marathi,hindi,physics,chemistry from students inner join test_marks on students.sid=test_marks.sid and students.sid='"+jTextField1.getText()+"' and test_marks.std='"+jComboBox1.getSelectedItem()+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
             if(rs.next()){
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else{
            JOptionPane.showMessageDialog(this,"Record  not found");
            }
            }
            /*else{
                JOptionPane.showMessageDialog(this,"Record already exist!");
            }*/
            else if(jComboBox1.getSelectedItem().equals("12th")){ 
       
            String sql="select test_marks.sid,students.sname,test_marks.english,marathi,hindi,physics,chemistry from students inner join test_marks on students.sid=test_marks.sid and students.sid='"+jTextField1.getText()+"' and test_marks.std='"+jComboBox1.getSelectedItem()+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
             if(rs.next()){
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else{
            JOptionPane.showMessageDialog(this,"Record  not found");
            }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(test_marksRetrieve.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
            //"select students.sname,test_marks.sid,english,marathi,hindi,science,history,geography,maths from students inner join test_marks on students.sid=test_marks.sid and students.sid='"+jTextField1.getText()+"'"
          
          //select sid,english,marathi,hindi,science,history,geography,maths from test_marks where sid='"+jTextField1.getText()+"'
        
       
        /*if(jComboBox1.getSelectedItem().equals("9th")){ 
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            String sql="select test_marks.sid,students.sname,test_marks.english,marathi,hindi,science,history,geography,algebra,geometry,sanskrit from students inner join test_marks on students.sid=test_marks.sid and students.sid='"+jTextField1.getText()+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            //if(jComboBox1.getSelectedItem().equals("9th")){}
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(test_marksRetrieve.class.getName()).log(Level.SEVERE, null, ex);
        }
         
            
          
          //select sid,english,marathi,hindi,science,history,geography,maths from test_marks where sid='"+jTextField1.getText()+"'
        }*/
      /*  if(jComboBox1.getSelectedItem().equals("10th")){ 
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            String sql="select test_marks.sid,students.sname,test_marks.english,marathi,hindi,science,history,geography,algebra,geometry,sanskrit from students inner join test_marks on students.sid=test_marks.sid and students.sid='"+jTextField1.getText()+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(test_marksRetrieve.class.getName()).log(Level.SEVERE, null, ex);
        }
         
            
          
          //select sid,english,marathi,hindi,science,history,geography,maths from test_marks where sid='"+jTextField1.getText()+"'
        }*/
        /*if(jComboBox1.getSelectedItem().equals("11th")){ 
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            String sql="select test_marks.sid,students.sname,test_marks.english,marathi,hindi,physics,chemistry from students inner join test_marks on students.sid=test_marks.sid and students.sid='"+jTextField1.getText()+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(test_marksRetrieve.class.getName()).log(Level.SEVERE, null, ex);
        }
         
            
          
          //select sid,english,marathi,hindi,science,history,geography,maths from test_marks where sid='"+jTextField1.getText()+"'
        }*/
       /* if(jComboBox1.getSelectedItem().equals("12th")){ 
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            String sql="select test_marks.sid,students.sname,test_marks.english,marathi,hindi,physics,chemistry from students inner join test_marks on students.sid=test_marks.sid and students.sid='"+jTextField1.getText()+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(test_marksRetrieve.class.getName()).log(Level.SEVERE, null, ex);
        }
         
            
          
          //select sid,english,marathi,hindi,science,history,geography,maths from test_marks where sid='"+jTextField1.getText()+"'
        }*/
       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test_marksRetrieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test_marksRetrieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test_marksRetrieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test_marksRetrieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test_marksRetrieve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}